# Generated by Django 3.0.4 on 2020-03-13 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('time_update', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 13, 28, 42, 650629, tzinfo=utc))),
                ('time_access', models.DateTimeField(default=datetime.datetime(2020, 3, 13, 13, 28, 42, 650629, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('tid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('txt', models.CharField(max_length=20)),
            ],
        ),
    ]
